<script>
  // This is the live contract; material changes require the notice promised below.
  const EFFECTIVE_DATE = '2 August 2026';
  const LAST_UPDATED = '2 August 2026';
</script>

<svelte:head>
  <title>Terms of Service: Supaclank</title>
  <meta name="description" content="The terms that govern the supaclank cloud service, websites, and mobile app." />
</svelte:head>

<div class="mx-auto w-full max-w-3xl px-5 pt-14 pb-24">
  <h1 class="text-3xl font-semibold tracking-tight sm:text-4xl">Terms of Service</h1>
  <p class="mt-2 text-sm text-dim">Effective {EFFECTIVE_DATE} · Last updated {LAST_UPDATED}</p>

  <div class="legal">
    <h2>1. Who we are</h2>
    <p>
      The supaclank service is operated by <strong>Absolutely Right AB</strong>, a Swedish limited
      company (aktiebolag), org. no. 559577-8233, Ofg 773b Billo, 106 46 Stockholm,
      Sweden ("supaclank", "we", "us"). You can
      reach us at <a href="mailto:support@supaclank.com">support@supaclank.com</a>.
    </p>

    <h2>2. What these terms cover</h2>
    <p>
      These terms are an agreement between you and us. They cover our websites (including
      supaclank.com), the clank mobile app, and the supaclank cloud service: the hosted sandboxes
      that let you build and run applications with an AI coding agent, without your own computer.
    </p>
    <p>They do <strong>not</strong> cover:</p>
    <ul>
      <li>
        <strong>The open-source clank CLI.</strong> It is licensed separately under its own
        open-source license, which alone governs your use of that software.
      </li>
      <li>
        <strong>Self-hosting.</strong> If you run clank on your own machines, you do not need an
        account or these terms, and none of your data reaches us.
      </li>
    </ul>

    <h2>3. Beta</h2>
    <p>
      The service is in beta. We develop it quickly, which means features evolve, sometimes
      break, and may be deprecated and removed as we learn what works; we fix problems as fast as
      we can, but
      day-to-day changes come without advance notice. For changes that materially reduce what the
      paid service does, we make reasonable efforts to notify you in advance, except when we need
      to act immediately for security, legal, or abuse reasons. If we ever discontinue the paid service entirely, we will email
      paying subscribers at least 30 days beforehand, so you have time to export your work (§7).
      Price changes also come with notice (see §9).
    </p>

    <h2>4. Your account</h2>
    <p>
      You need an account for the cloud service. Keep your sign-in credentials secure; you are
      responsible for activity under your account. Provide accurate information and keep it up to
      date. You must be at least 13 years old; if you are under 18, you need a parent's or
      guardian's consent.
    </p>

    <h2>5. Your content is yours</h2>
    <p>
      You own the code, applications, images, and other content you create or upload. That
      includes, to the extent we can grant or confirm it, output generated by an AI agent working
      for you. We claim no ownership of any of it.
    </p>
    <p>
      You give us only the limited license we need to run the service for you: to store, execute,
      transmit, back up, and display your content, at your direction. If you send us feedback or
      suggestions, we may use them without obligation to you.
    </p>
    <p>
      The service itself (our software, sites, and branding) belongs to us and our licensors.
    </p>

    <h2>6. AI agents and your AI provider</h2>
    <p>
      clank works by running a coding agent (by default, Anthropic's Claude Code CLI) on your
      sandbox. You connect the agent to <strong>your own AI provider account</strong>: we start the
      provider's device-authorization flow, and the resulting credential is stored on your sandbox
      and used by the agent on your behalf.
    </p>
    <ul>
      <li>
        Your prompts and relevant project context are sent from your sandbox directly to the
        provider you chose. That exchange is governed by your agreement with that provider, not by
        these terms.
      </li>
      <li>
        You are responsible for complying with your provider's terms and usage policies, and for
        any fees your provider charges you.
      </li>
      <li>
        AI-generated code and content can be wrong, insecure, or infringing.
        <strong>Review output before you rely on it, ship it, or run it somewhere that matters.</strong>
        You are responsible for what you deploy.
      </li>
      <li>
        Providers are independent services. We are not responsible for their availability, rate
        limits, pricing, or their decisions about your account, and an outage at your provider is
        not an outage of ours.
      </li>
    </ul>

    <h2>7. Your sandbox</h2>
    <p>
      The cloud service gives you a personal sandbox: an isolated environment where your projects
      live and your agent runs. It is a development environment, not a hosting service: use it to
      build, run, and preview the applications you create with clank, not to serve production
      traffic to end users, and not as a general-purpose host for unrelated workloads.
    </p>
    <p>
      The sandbox runs on infrastructure we administer. Who can access it, and when, is described
      in our <a href="/privacy">Privacy Policy</a>. In short: automated maintenance keeps it
      running, and people at supaclank access its contents only to debug at your request, to
      investigate abuse or security incidents, or when legally compelled.
    </p>
    <p>Lifecycle:</p>
    <ul>
      <li>
        <strong>While subscribed</strong>, your sandbox and its contents persist between sessions.
      </li>
      <li>
        <strong>When your subscription ends</strong>, your sandbox is suspended, not deleted:
        resubscribe and pick up where you left off. We may eventually clean up sandboxes that stay
        inactive, but never sooner than 30 days after the subscription ends, so export anything you
        need if you're leaving for good.
      </li>
      <li>
        <strong>Deleting your account</strong> destroys your sandbox and everything on it
        immediately (see the <a href="/privacy">Privacy Policy</a>).
      </li>
      <li>
        <strong>Your code is portable.</strong> It lives in git; push it anywhere, anytime while
        subscribed. If you need help exporting, contact
        <a href="mailto:support@supaclank.com">support@supaclank.com</a> before you cancel.
      </li>
    </ul>

    <h2>8. Acceptable use</h2>
    <p>Don't use the service to:</p>
    <ul>
      <li>break the law, or infringe anyone's rights (including intellectual property);</li>
      <li>distribute malware, phish, spam, or attack, probe, or disrupt others' systems;</li>
      <li>mine cryptocurrency, or otherwise abuse compute, storage, or network resources;</li>
      <li>resell, share, or provide the service to third parties as your own offering;</li>
      <li>circumvent usage limits, billing, or security measures.</li>
    </ul>
    <p>
      Applications you build can be served to the web through infrastructure we operate (for
      example, preview links). If we receive credible reports of abusive or unlawful content served
      this way, we may remove it or suspend serving it, and will tell you when practicable. Report
      abuse to <a href="mailto:abuse@supaclank.com">abuse@supaclank.com</a>.
    </p>

    <h2>9. Fees, trials, cancellation, refunds</h2>
    <ul>
      <li>
        <strong>Price.</strong> The paid plan costs the price shown at checkout, billed as a
        recurring subscription by our payment provider, Stripe. Subscriptions renew automatically
        until cancelled.
      </li>
      <li>
        <strong>Trials.</strong> When we offer a free trial, its length and conditions are shown at
        sign-up. If a trial requires no payment method, it simply ends unless you subscribe.
      </li>
      <li>
        <strong>Cancellation.</strong> Cancel anytime; cancellation takes effect at the end of the
        current billing period. Apart from your statutory rights, we do not refund partial periods.
      </li>
      <li>
        <strong>EU/EEA withdrawal right.</strong> If you are a consumer in the EU/EEA, you may
        withdraw from your first purchase within 14 days without giving a reason, by emailing
        <a href="mailto:support@supaclank.com">support@supaclank.com</a>. You agree the service
        starts immediately; if you withdraw, we refund the price minus a proportional amount for
        the time already elapsed. Renewals do not trigger a new withdrawal right.
      </li>
      <li>
        <strong>Price changes.</strong> We will give you at least 30 days' notice by email before a
        price increase, which applies from your next billing period after the notice. If you don't
        agree, cancel before it takes effect.
      </li>
    </ul>

    <h2>10. Suspension and termination</h2>
    <p>
      You can stop using the service and delete your account at any time. We may suspend or
      terminate your access if you materially breach these terms, if we must for legal or security
      reasons, or if the service is discontinued (per §3). Unless the breach is severe or the law
      prevents it, we will notify you and give you a chance to fix the problem first. After
      termination, the sandbox lifecycle in §7 applies.
    </p>

    <h2>11. Disclaimers</h2>
    <p>
      The service is provided <strong>"as is" and "as available"</strong>, without warranties of
      any kind, to the extent permitted by law. We do not promise uninterrupted or error-free
      operation, and the beta service has no uptime commitment. AI output is probabilistic and can
      be wrong; §6 applies. Nothing in this section limits rights you have as a consumer under
      mandatory law.
    </p>

    <h2>12. Liability</h2>
    <p>
      Nothing in these terms excludes or limits liability for gross negligence, willful misconduct,
      or anything else that cannot be excluded or limited under applicable law. Subject to that,
      our total liability for claims arising out of the service in any 12-month period is capped at
      the fees you paid us in that period (or, if you have paid nothing, SEK 500), and neither of
      us is liable for indirect or consequential losses (such as lost profits, revenue, or data)
      that were not reasonably foreseeable.
    </p>

    <h2>13. Changes to these terms</h2>
    <p>
      We may update these terms as the service evolves. For material changes we will give you at
      least 30 days' notice by email before they take effect; minor changes (such as clarifications
      or new features) may apply once posted. If you don't agree with a change, cancel before it
      takes effect. The current version always lives at this page, and its history is public in our
      repository.
    </p>

    <h2>14. Governing law and disputes</h2>
    <p>
      Swedish law governs these terms. If we have a dispute, talk to us first: email
      <a href="mailto:support@supaclank.com">support@supaclank.com</a> and we will try to resolve
      it with you informally within 30 days. Failing that, disputes are resolved by Swedish courts
      with Stockholm District Court as the first instance, except that if you are a consumer, you
      keep any right under mandatory law to bring or defend a dispute where you live. Consumers in
      Sweden can also turn to the National Board for Consumer Disputes (Allmänna
      reklamationsnämnden, arn.se).
    </p>

    <h2>15. The boring-but-necessary bits</h2>
    <ul>
      <li>If part of these terms is found unenforceable, the rest still applies.</li>
      <li>
        Not enforcing a term at some moment doesn't waive our right to enforce it later.
      </li>
      <li>
        You may not assign this agreement without our consent; we may assign it in connection with
        a merger, acquisition, or sale, with notice to you.
      </li>
      <li>
        Terms that by their nature should outlive this agreement do so, including your ownership
        of your content (§5), the disclaimers (§11), the liability cap (§12), and the dispute
        terms (§14).
      </li>
      <li>
        These terms and the <a href="/privacy">Privacy Policy</a> are the whole agreement between
        us about the service.
      </li>
    </ul>

    <h2>16. Contact</h2>
    <p>
      Questions about these terms:
      <a href="mailto:support@supaclank.com">support@supaclank.com</a>.
    </p>
  </div>
</div>

<style>
  /* Long-form legal prose shares the site's theme tokens without repeating
     utility classes on every paragraph, list, and heading. */
  .legal h2 {
    margin: 2.5rem 0 0.75rem;
    font-size: 1.25rem;
    font-weight: 600;
    letter-spacing: -0.01em;
    color: var(--color-ink);
  }
  .legal p,
  .legal ul {
    margin: 0.75rem 0;
    line-height: 1.65;
    color: var(--color-muted);
  }
  .legal ul {
    padding-left: 1.25rem;
    list-style: disc;
  }
  .legal li {
    margin: 0.4rem 0;
  }
  .legal li::marker {
    color: var(--color-dim);
  }
  .legal strong {
    font-weight: 600;
    color: var(--color-ink);
  }
  .legal a {
    color: var(--color-ink);
    text-decoration: underline;
    text-decoration-color: var(--color-line);
    text-underline-offset: 3px;
    transition: text-decoration-color 120ms;
  }
  .legal a:hover {
    text-decoration-color: var(--color-brand);
  }
</style>
